language = "en"
open_last_loaded_on_startup = true
generate_thumbs = true
thumb_cache_size = 500
cached_thumb_quality = 80
cached_thumb_resolution = 256
autoplay = true
loop = true
show_filenames_in_grid = true
show_category_sidebar = false
show_preview_created_date = false
show_preview_modified_date = false
show_preview_filename = false
show_preview_media_info = false
page_size = 100
infinite_scroll = true
show_filepath = 1
tag_click_action = 0
theme = 2
splash = "default"
windows_start_command = false
selected_tag_highlight_color = "#4da3ff"
title_overlay_font_size_adjust = 0
date_format = "%x"
hour_format = true
zero_padding = true
